# Generated by Django 4.0 on 2023-11-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_person_profile_person_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Person',
            new_name='person',
        ),
    ]
